language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
# Build
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user 
  # Tagging
  - docker tag udagram-api-feed wawerudev/udagram-api-feed:latest
  - docker tag udagram-api-user wawerudev/udagram-api-user:latest
  - docker tag udagram-frontend wawerudev/udagram-frontend:latest
  - docker tag reverseproxy wawerudev/udagram-reverseproxy:latest
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wawerudev/udagram-api-feed:latest
  - docker push wawerudev/udagram-api-user:latest
  - docker push wawerudev/udagram-frontend:latest
  - docker push wawerudev/udagram-reverseproxy:latest